#!/bin/bash

clear 


echo -------------------------------------------------
cat /etc/hosts  | head -n 2
cat /etc/hostname 
echo 
#echo -n " enter the hostname:"
read $1

echo $1 > /etc/hostname
sleep 3
sed -i.bak '/127.0.1.1/d' /etc/hosts
echo 'changing hostname.....'
echo 
sleep 1
sed -i.bak "/127.0.0.1/a 127.0.1.1    $1" /etc/hosts
 
sleep 1
echo 
cat /etc/hosts  | head -n 2
echo      
hostnamectl set-hostname "$1"
cat /etc/hostname
