


- name: copying file
  copy: src="{{ item }}"  dest=/tmp/
  ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
  with_fileglob:
    - "/home/soft/files/*"
  tags: copy_files

- name: copying director
  copy: src=chrome  dest=/tmp/chrome 
  ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
#  with_fileglob:
#    - "/home/soft/files/*"
  tags: copy_dir

- name: synchronize director
  synchronize: 
        src: chrome  
        dest: /tmp 
        recursive: yes
  ignore_errors: yes
  
#  archive: yes
#  rsync_opts
#  rsync_path
#  set_remote_user
#  with_fileglob:
#    - "/home/soft/files/*"
  tags: sync_dir



- name: copying notepad
  block: 
  - name: mkdir
    shell: mkdir -p /tmp/softs
  - name: install notepad
    copy: src="{{ item }}"  dest=/tmp/softs
    ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
    with_fileglob:
     - "/home//tets/roles/soft/files/notepad/*"
    register: copyf
  
  - name: installing notepad
    shell: | 
             dpkg -i /tmp/softs/notepadqq-common_1.2.0-1~trusty1_all.deb   
             dpkg -i /tmp/softs/notepadqq_1.2.0-1~trusty1_amd64.deb
             apt-get install -f -y


  - name: del files
    shell: rm -rf /tmp/softs
    when: copyf.changed 
  tags: notepad  
  
- name: copying chrome
  block: 
  - name: mkdir
    shell: mkdir -p /tmp/softs
  - name: install chrome
    copy: src="{{ item }}"  dest=/tmp/softs
    ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
    with_fileglob:
     - "/home//tets/roles/soft/files/chrome/*"
    register: chromef
  
  - name: installing chrome
    shell: |  
             dpkg -i /tmp/softs/google-chrome* 
             apt-get install -f -y 
  - name: del files
    shell: rm -rf /tmp/softs
    when: chromef.changed 
  tags: chrome   

  
- name: copying citrix
  block: 
  - name: mkdir
    shell: mkdir -p /tmp/softs
  - name: install citrix
    copy: src="{{ item }}"  dest=/tmp/softs
    ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
    with_fileglob:
     - "/home//tets/roles/soft/files/citrix/*"
    register: citrixf
  
  - name: installing citrix
    shell: |  
             dpkg -i /tmp/softs/icaclient_13.10.0.20_amd64.deb
             apt-get install -f  -y
             bash /tmp/citrix1
             bash /tmp/citrix
  - name: del files
    shell: rm -rf /tmp/softs
    when: citrixf.changed 
  tags: citrix

- name: copying horizon
  block: 
  - name: mkdir
    shell: mkdir -p /tmp/softs
  - name: install horizon
    copy: src="{{ item }}"  dest=/tmp/softs
    ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
    with_fileglob:
     - "/home/tets/roles/soft/files/VMware-Horizon-Client-4.6.0-6617224.x64.bundle"
    register: horizonf
  
  - name: installing horizon
    shell: |  
             sh '/tmp/VMware-Horizon-Client-4.6.0-6617224.x64.bundle' --console --eulas-agreed --required
             
  - name: del files
    shell: rm -rf /tmp/softs
    when: horizonf.changed 
  tags: horizon

- name: copying dbeaver
  block: 
  - name: mkdir
    shell: mkdir -p /tmp/softs
  - name: install dbeaver
    copy: src="{{ item }}"  dest=/tmp/softs
    ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
    with_fileglob:
     - "/home/files/dbeaver/*"
    register: dbeaverf
  
  - name: installing dbeaver
    shell: |  
             dpkg -i /tmp/softs/*
             apt-get install -f
             
  - name: del files
    shell: rm -rf /tmp/softs
    when: dbeaverf.changed 
  tags: dbeaver


  - name: install mcafee
  block: 
  - name: checking mcafee
    shell: service ma status | grep Active | awk '{print $2}'
    ignore_errors: yes
    register: mcafee_status
  - debug: msg="{{ mcafee_status.stdout }}"
#    when: mcafee_status.stdout==""
  - debug: msg="mcafee is  already installed"
    when: mcafee_status.stdout=="active" or mcafee_status.stdout=="inactive" 


  - name: mkdir
    shell: mkdir -p /tmp/softs
    when: mcafee_status.stdout==""
  - name: copying mcafee
    copy: src="{{ item }}"  dest=/tmp/softs
    ignore_errors: yes
#  with_items:
#   - SoapUI-x64-5.4.0.sh
#   - App*
    with_fileglob:
     - "/home/roles/soft/files/mcafee/*"
    register: mcafeef
    when: mcafee_status.stdout==""
  
  - name: installing mcafee
    shell: bash /tmp/softs/* -i 
    ignore_errors: yes
    when: mcafeef.changed         
  - name: del files
    shell: rm -rf /tmp/softs
    when: mcafeef.changed 
  tags: mcafee
  


  when: check_copy_file=="yes"
